config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  resources :forecasts, only: [:index, :create, :show]

  Rails.application.routes.draw do
    mount Sidekiq::Web => '/sidekiq'
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "forecasts#index"
end

app/models/forecast.rb
# == Schema Information
#
# Table name: forecasts
#
#  id            :bigint           not null, primary key
#  address       :string
#  data          :jsonb
#  forecast_data :jsonb
#  zipcode       :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
# Indexes
#
#  index_forecasts_on_zipcode  (zipcode)
#

# Forecast
# The primary class for fetching weather/forecast information
# .forecast_data is used for storing upcoming weather, while .data is used for storing the current weather and location information
# "!" methods (e.g. request_and_assign_forecast_data!) trigger immediate requests, use async methods to schedule jobs and allow immediate returns
#
#
# TODO
# - Refactor current weather and location information into different fields for more clear and scalable access
# - Remove cached virtual attribute, it is deprecated
# - Consolidate forecast and current requests into one call
# - Simply data storage to retain only required information (e.g. no need to retain pressure or other forecast data)

class Forecast < ApplicationRecord
  EXPIRATION = 30.minutes.freeze

  attr_accessor :cached

  scope :not_expired, -> { where("updated_at > ?", EXPIRATION.ago) }
  scope :index_list, -> { not_expired.order(created_at: :desc).limit(25) }

  validate :validate_address

  after_update_commit { broadcast_update_to "forecast" }
  before_save :request_zipcode_async, if: :will_save_change_to_data?

  def initialize(attributes = {})
    super(attributes)
    self.cached = false
  end

  def request_and_assign_forecast_data!
    requester = Forecast::Requester.new(self.address)
    self.data = requester.get_current_weather_by_address!

    requester.get_forecast_by_address!
    self.forecast_data = requester.get_forecast_by_address!
  end

  def request_and_assign_zipcode!
    requester = Forecast::GeocodeRequester.new(self.address)
    raise Forecast::GeocodeRequester::RequestInvalidError unless requester.valid_response?

    self.zipcode = requester.parse_for_zipcode
  end

  def request_forecast_async = ForecastRequesterJob.perform_now(self.id)

  def request_zipcode_async = GeocodeRequesterJob.perform_now(self.id)

  def expiry_date = self.updated_at + EXPIRATION

  def expired? = Time.current >= (self.updated_at + EXPIRATION)

  def cached? = self.cached

  def serialized_current_weather_data = ForecastDataSerializer.new(data)

  # TODO
  # def serialized_forecast_data = ForecastDataSerializer.new(forecast_data)

  private

  def validate_address
    return if address.match?(/\A[A-Za-z0-9'\.\-\s,]+\z/)

    self.errors.add(:address, "Must be a valid address which cannot contain any symbols")
  end

end

app/models/forecast/geocode_requester.rb
# frozen_string_literal: true

require "net/http"
require "json"
require "uri"

# Use GeocodeRequester to interface with HERE API to receive location information.
# It is primarily used for requesting a zip code (postal code).
# Current refers to the current conditions at a location, while Forecast is the upcoming weather
# Example usage:
#   geo_requester = Forecast::GeocodeRequester.new(forecast.address)
#   geo_requester.parse_for_zipcode => json_api_response
#
# # Note that on initialization, the request is sent. Refactor as appropriate if the expectations on GeocodeRequester change.
#
# For error checking, use #valid_response?
# RequestInvalidError can be used for specific handling

class Forecast::GeocodeRequester
  class RequestInvalidError < RuntimeError; end

  BASE_URI = "https://geocode.search.hereapi.com/v1/".freeze
  API_KEY = (ENV["HERE_API_KEY"] || "RUIsEe39r2gySGLNw6WyyHzvqOlHJxAsloc-M9g1jhE").freeze

  attr_accessor :response, :address

  def initialize(address)
    @address = address
    request_geocode_information!
  end

  def request_geocode_information!
    uri = URI("#{BASE_URI}/geocode")
    params = { q: @address, apiKey: API_KEY }
    uri.query = URI.encode_www_form(params)

    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true

    request = Net::HTTP::Get.new(uri)
    @response = http.request(request)
  end

  def parse_for_zipcode
    zip = serialized_response.zipcode
    return "" if zip.nil?

    # return only the first 5 of the zip-code, note: only have tested within USA
    zip.match /\d{5}/
  end

  def serialized_response
    return { error: @response.message } unless valid_response?

    GeocodeSerializer.new(JSON.parse(@response.body))
  end

  def valid_response? = @response.is_a?(Net::HTTPSuccess)
end

app/models/forecast/requester.rb
# frozen_string_literal: true
require "net/http"
require "json"
require "uri"

# Use Requester to interface with WeatherAPI to receive forecast information
# Current refers to the current conditions at a location, while Forecast is the upcoming weather
# Example usage:
#   requester = Forecast::Requester.new(forecast.address)
#   requester.response.body => json_api_response
#
# Note that on initialization, the request is sent. Refactor as appropriate if the expectatinos on Requester change.
#
# For error checking, use #valid_response?
# RequestInvalidError can be used for specific handling

class Forecast::Requester
  class RequestInvalidError < RuntimeError; end

  BASE_URI = "https://api.weatherapi.com/v1"
  API_KEY = ENV["API_KEY"] || "eb215054a2364e638d5202918241510"

  attr_accessor :current_response, :address, :forecast_response

  def initialize(address)
    @address = address
  end

  def get_current_weather_by_address!
    uri = URI("#{BASE_URI}/current.json")
    params = { q: @address, key: API_KEY }
    uri.query = URI.encode_www_form(params)
    @response = Net::HTTP.get_response(uri)
    raise RequestInvalidError unless valid_response?

    JSON.parse(@response.body)
  end

  def get_forecast_by_address!
    uri = URI("#{BASE_URI}/forecast.json")
    params = { q: @address, key: API_KEY, days: 3 }
    uri.query = URI.encode_www_form(params)
    @forecast_response = Net::HTTP.get_response(uri)
    raise RequestInvalidError unless valid_forecast_response?

    JSON.parse(@forecast_response.body)
  end

  def serialized_response
    return { error: @response.message } unless valid_response?

    ForecastDataSerializer.new(@response.body)
  end

  def serialized_forecast_response
    return { error: @forecast_response.message } unless valid_forecast_response?

    ForecastDataSerializer.new(@forecast_response.body)
  end

  def valid_response? = @response.is_a?(Net::HTTPSuccess)

  def valid_forecast_response? = @forecast_response.is_a?(Net::HTTPSuccess)

end

app/controllers/forecasts_controller.rb
class ForecastsController < ApplicationController

  # GET /forecasts/1 or /forecasts/1.json
  def show
    @forecast = Forecast.find(params[:id])
    retrieve_or_indicate_cache_is_valid
    @forecast.reload
  end

  def index
    @forecasts = Forecast.index_list
  end

  def create
    @forecast = find_by_address_or_zip

    # render forecast if we have it saved already
    if @forecast.present?
      retrieve_or_indicate_cache_is_valid
      redirect_to @forecast and return
    end

    @forecast = Forecast.new(address: params[:address])

    unless @forecast.valid?
      flash.now[:error] = @forecast.errors.full_messages.to_sentence
      return render :index
    end

    respond_to do |format|
      if @forecast.save
        @forecast.request_forecast_async # requires ID
        format.html { redirect_to @forecast }
        format.json { render :show, status: :ok, location: @forecast }
      else
        @forecasts = Forecast.index_list
        format.html { render :index, error: @forecast.errors.full_messages.to_sentence }
        format.json { render json: @forecast.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def retrieve_or_indicate_cache_is_valid
    return @forecast.request_forecast_async if @forecast.expired?

    flash[:info] = "Retrieving a cached forecast"
  end

  def find_by_address_or_zip
    return Forecast.find_by(zipcode: params[:address]) if param_is_zipcode?

     Forecast.find_by(address: params[:address])
  end

  def param_is_zipcode?
    params[:address].match? /\d{5}/
  end

  # Only allow a list of trusted parameters through.
  def forecast_params
    params.require(:forecast).permit(:address)
  end
end

app/helpers/forecasts_helper.rb
module ForecastsHelper
  def icon_map(key)
    case key
    when /uv/; "☀️"
    when /cloud/; "☁️"
    when /temp/; "🌡️"
    when /vis/; "👁️"
    when /precip/; "🌧️"
    when /dewpoint/; nil
    when /pressure/; "💎"
    when /wind_degree/; "🧭"
    when /wind_chill/; "🥶"
    end
  end

  def location_labelize(key)
    str = case key
          when /lat/; "Latitude"
          when /lon/; "Longitude"
          when /name/; "Location"
          when /tz_id/; "Timezone"
          when /region/; "Region"
          when /country/; "Country"
          when /localtime/; "Local time"
          end
    str + ":"
  end

  def forecast_labelize(key)
    case key
    when /uv/; "UV"
    when /cloud/; "Cloud"
    when /temp/; "Temperature"
    when /feels/; "Feels like"
    when /vis/; "Visibility"
    when /precip/; "Precipitation"
    when /dewpoint/; "Dew point"
    when /pressure/; "Pressure"
    when /wind_degree/; "Wind degree"
    when /wind_chill/; "Wind chill"
    when /gust/; "Gust"
    when /humidity/; "Humidity"
    when /wind_dir/; "Wind direction"
    when /wind_mph/; "Wind (mph)"
    when /heat_index/; "Heat index"
    when /windchill_f/; "Wind-chill"
    else
      key
    end
  end
end

app/views/forecasts/_current_weather_data.html.erb
<%# TODO - prepare this in the controller for cleaner access  %>
<% three_day_forecast = forecast.forecast_data.dig("forecast", "forecastday") %>
<h2 class="text-muted">3 Day Weather Forecast</h2>

<div class="row">
  <% three_day_forecast.each do |daily_forecast| %>
    <div class="col border border-2 rounded p-4 mx-2">
      <%= content_tag :h3, daily_forecast["date"], class: "fs-5" %>
      <% day = daily_forecast["day"] %>
      <%= content_tag :h4, "#{day["avgtemp_f"]}°", class: 'display-4' %>
      <p>
        <strong>High: </strong> <%= "#{day["maxtemp_f"]}°" %>
        <strong>Low: </strong> <%= "#{day["mintemp_f"]}°" %>
      </p>

    </div>
  <% end %>
</div>

app/views/forecasts/_forecast.html.erb
<h1>
  <strong class="fs-6 text-muted">Weather for</strong>
  <br>
  <%= forecast.address %>

  <% unless forecast.expired? %>
      <span class="badge bg-light text-dark fs-6 align-middle">
        Cached – Next refresh in
        <%= distance_of_time_in_words(forecast.expiry_date, Time.current) %>
      </span>
  <% end %>
</h1>

<div id="current-weather">
  <% if forecast.data.present? %>
    <%= render 'forecast_data', forecast: forecast %>
  <% else %>
    <p>No weather data available yet...refreshing</p>
    <script>
      setTimeout(function() {
        window.location.reload();
      }, 1000);
    </script>
  <% end %>
</div>

<div id="forecast" class="mt-5">
  <% if forecast.forecast_data.present? %>
    <%= render 'current_weather_data', forecast: forecast %>
  <% else %>
    <p>No forecast data available yet...refreshing</p>
  <% end %>
</div>

app/views/forecasts/_forecast_data.html.erb
<% s_data = forecast.serialized_current_weather_data %>

<div class="lead">
  <%= s_data.name %>, <%= s_data.region %> <%= forecast.zipcode %>
  <p><%= s_data.country %></p>
  <p class="font-monospace fs-6"><%= s_data.latitude %>,<%= s_data.longitude %></p>
</div>

<div class="border border-2 rounded mt-5 p-4">

  <div class="row align-items-start">
    <div class="col">
      <div class="row">
        <div class="col-lg-6">
          <%= content_tag :h1, "#{s_data.temp_f}°", class: 'display-1' %>
        </div>

        <div class="col col-lg-6">
          <%= content_tag :span, s_data.condition['text'], class: 'display-6 align-middle' %>
          <%= image_tag(
                s_data.condition['icon'],
                alt: s_data.condition['text']
              ) %>
        </div>
      </div>
    </div>
    <div class="col my-auto mx-auto">
      <%= content_tag :p do %>
        <strong>🌧 Precipitation:</strong> <%= "#{s_data.precip_in} in" %>
      <% end %>
      <%= content_tag :p do %>
        <strong>💧Humidity:</strong> <%= "#{s_data.humidity}" %>
      <% end %>
      <%= content_tag :p do %>
        <strong>🌬️ Wind:</strong> <%= "#{s_data.wind_mph} mph #{s_data.wind_dir}" %>
      <% end %>
    </div>

  </div>
</div>

app/views/forecasts/index.html.erb
<p style="color: green"><%= notice %></p>
<p style="color: red"><%= flash[:error] %></p>

<div class="text-center mt-5">
  <h1>What's the Weather?</h1>
  <div data-turbo="false">
    <%= form_with url: forecasts_path do |f| %>
      <%= f.label :address, "Enter an Address to see your forecast", class: 'fs-6 fw-bold mt-5 mb-2' %>
      <br>
      <%= f.text_field :address, style: "font-size: 1.5em; width: 50%" %>
    <% end %>
  </div>
</div>


<% if @forecasts&.any? %>
  <h2 class="mt-5 fs-5">Previous requests</h2>
  <div id="forecasts">
    <% @forecasts.each do |forecast| %>
      <%= link_to forecast, class: "text-decoration-none", data: {turbo: false} do %>
        <div class="card my-3">
          <div class="card-body">
            <%= content_tag :h5, "#{forecast.address} - #{time_ago_in_words(forecast.updated_at)} ago" %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/forecasts/show.html.erb
<% if flash[:info] %>
  <div class="alert alert-info">
    <%= flash[:info] %>
  </div>
<% end %>
<p style="color: green"><%= notice %></p>
<%#= debug @forecast if ENV["RAILS_ENV"] == 'development' %>

<div class="mb-5">
  <%= link_to "← Back to Home", root_path %>
</div>

<% content_for :title, "Forecast for: #{@forecast.address}" %>

<%= turbo_stream_from "forecast" %>
<div id="forecast">
  <%= render @forecast %>
</div>